// Generated from Projeto.g4 by ANTLR 4.5.3
package autogenerated;

import org.antlr.v4.runtime.tree.ParseTreeListener;

/**
 * This interface defines a complete listener for a parse tree produced by
 * {@link ProjetoParser}.
 */
public interface ProjetoListener extends ParseTreeListener {
	/**
	 * Enter a parse tree produced by the {@code Program}
	 * labeled alternative in {@link ProjetoParser#pgm}.
	 * @param ctx the parse tree
	 */
	void enterProgram(ProjetoParser.ProgramContext ctx);
	/**
	 * Exit a parse tree produced by the {@code Program}
	 * labeled alternative in {@link ProjetoParser#pgm}.
	 * @param ctx the parse tree
	 */
	void exitProgram(ProjetoParser.ProgramContext ctx);
	/**
	 * Enter a parse tree produced by the {@code DefineBin}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void enterDefineBin(ProjetoParser.DefineBinContext ctx);
	/**
	 * Exit a parse tree produced by the {@code DefineBin}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void exitDefineBin(ProjetoParser.DefineBinContext ctx);
	/**
	 * Enter a parse tree produced by the {@code DefineUn}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void enterDefineUn(ProjetoParser.DefineUnContext ctx);
	/**
	 * Exit a parse tree produced by the {@code DefineUn}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void exitDefineUn(ProjetoParser.DefineUnContext ctx);
	/**
	 * Enter a parse tree produced by the {@code Undefine}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void enterUndefine(ProjetoParser.UndefineContext ctx);
	/**
	 * Exit a parse tree produced by the {@code Undefine}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void exitUndefine(ProjetoParser.UndefineContext ctx);
	/**
	 * Enter a parse tree produced by the {@code IfDefined}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void enterIfDefined(ProjetoParser.IfDefinedContext ctx);
	/**
	 * Exit a parse tree produced by the {@code IfDefined}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void exitIfDefined(ProjetoParser.IfDefinedContext ctx);
	/**
	 * Enter a parse tree produced by the {@code IfNotDefined}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void enterIfNotDefined(ProjetoParser.IfNotDefinedContext ctx);
	/**
	 * Exit a parse tree produced by the {@code IfNotDefined}
	 * labeled alternative in {@link ProjetoParser#dir}.
	 * @param ctx the parse tree
	 */
	void exitIfNotDefined(ProjetoParser.IfNotDefinedContext ctx);
	/**
	 * Enter a parse tree produced by the {@code TextID}
	 * labeled alternative in {@link ProjetoParser#cod}.
	 * @param ctx the parse tree
	 */
	void enterTextID(ProjetoParser.TextIDContext ctx);
	/**
	 * Exit a parse tree produced by the {@code TextID}
	 * labeled alternative in {@link ProjetoParser#cod}.
	 * @param ctx the parse tree
	 */
	void exitTextID(ProjetoParser.TextIDContext ctx);
	/**
	 * Enter a parse tree produced by the {@code TextNumber}
	 * labeled alternative in {@link ProjetoParser#cod}.
	 * @param ctx the parse tree
	 */
	void enterTextNumber(ProjetoParser.TextNumberContext ctx);
	/**
	 * Exit a parse tree produced by the {@code TextNumber}
	 * labeled alternative in {@link ProjetoParser#cod}.
	 * @param ctx the parse tree
	 */
	void exitTextNumber(ProjetoParser.TextNumberContext ctx);
	/**
	 * Enter a parse tree produced by the {@code TextSymbol}
	 * labeled alternative in {@link ProjetoParser#cod}.
	 * @param ctx the parse tree
	 */
	void enterTextSymbol(ProjetoParser.TextSymbolContext ctx);
	/**
	 * Exit a parse tree produced by the {@code TextSymbol}
	 * labeled alternative in {@link ProjetoParser#cod}.
	 * @param ctx the parse tree
	 */
	void exitTextSymbol(ProjetoParser.TextSymbolContext ctx);
}